run_command(['bash', meson.global_source_root() + '/core/alchemist/generate_files.sh'], check: true)

alchemist_sources = [
  'elements/types.cpp',
  'elements/base.cpp',
  'elements/base_element.cpp',
  'elements/inventory_element.cpp',
  'elements/place.cpp',
  'elements/scroll.cpp',
  'elements/element.cpp',
  'elements/ingredient.cpp',
  'elements/product.cpp',
  'elements/base_animal.cpp',
  'elements/animal.cpp',
  'elements/base_plant.cpp',
  'elements/plant.cpp',
  'elements/field.cpp',
  'elements/barn.cpp',
  'names.cpp',
  'el_list.cpp',
  'npc_talk.cpp',
  'properties.cpp',
  'skills.cpp',
  'serialization.cpp',
  'object.cpp'
  ]


