#!/bin/bash

cd "$(dirname "$(realpath "$0")")"

echo "// autogenerated file, don't modify!

#ifndef PACKET_TYPE_H
#define PACKET_TYPE_H

using PacketType = unsigned char;" > packet_types.h
#########################################################
echo "// autogenerated file, don't modify!
#include \"packet_types.h\"
#include <stdio.h>
#include <assert.h>
int CONSOLE_LOG(const char * fmt, ...);

const char * packet_type_names[]={ " > packet_types.cpp
#########################################################
val=0

for p in `cat packet_types.txt`
do
    echo "constexpr static const PacketType $p = $val;" >> packet_types.h
    val=$(($val + 1))
    echo "\"$p\"," >> packet_types.cpp
done
#########################################################
echo -e "\nextern const char * packet_type_names[];
void show_packet_type_name(char what, unsigned char i);
extern int trace_network;
#endif" >> packet_types.h
#########################################################
echo "};

int trace_network;

void show_packet_type_name(char what, unsigned char i)
{
    trace_network %= 4;
    switch (trace_network)
    {
        case 3: if (i == PACKET_PLAYER_UPDATE || i == PACKET_KEEP_ALIVE) return;
        case 2: if (i == PACKET_PLAYER_UPDATE) return;
        case 1: 
           CONSOLE_LOG(\"%c %d -> %s\\n\", what, i, i < PACKET_COUNT ? packet_type_names[i] : \"ERROR\" ); break;
        default: break;
    }  
    assert(i < PACKET_COUNT);
}
" >> packet_types.cpp
