#ifndef WORLD_PARAMS_H
#define WORLD_PARAMS_H

#define WORLD_SIZE 256
#define WORLD_CENTER WORLD_SIZE / 2
#define CHUNK_SIZE 17

#define BASE_PLANTS 21
#define BASE_ANIMALS 3

#endif // WORLD_PARAMS_H
