client_common_sources=[
    'net.cpp',
    'net2d.cpp',
    'game.cpp',
    'players.cpp',
    'text.cpp',
    'packets.cpp'
]
client_common_2d_sources=[
    'player_actions.cpp',
    'npc.cpp',
    'texture.cpp',
    'render.cpp',
    'alchemist2d.cpp',
    'being2d.cpp',
    'inputs.cpp',
    'window.cpp'
]
